services:
  - type: web
    name: africana-ntgr
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      gunicorn africana.wsgi:application