# Generated by Django 5.0.14 on 2025-07-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id_code',
            field=models.CharField(blank=True, help_text='A unique code for the student, e.g., generated in-app or by teacher.', max_length=50, null=True),
        ),
    ]
