# Generated by Django 5.0.14 on 2025-08-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='temp_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
