# Generated by Django 5.0.14 on 2025-08-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teacher_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='temp_field',
        ),
    ]
