# Generated by Django 5.0.14 on 2025-07-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_student_id_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(blank=True, help_text='Ethereum wallet address (0x...)', max_length=42, null=True, unique=True),
        ),
    ]
