# Generated by Django 5.0.14 on 2025-08-17 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_alter_lesson_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
