# Generated by Django 5.0.14 on 2025-08-17 03:00

from django.db import migrations


def clean_student_progress_data(apps, schema_editor):
    StudentProgress = apps.get_model('api', 'StudentProgress')
    for progress in StudentProgress.objects.all():
        progress_data = progress.overall_progress_data
        if progress_data:
            for lesson_uuid, data in progress_data.items():
                if isinstance(data, dict) and data.get('last_attempt_date') == 'N/A':
                    data['last_attempt_date'] = None
            progress.overall_progress_data = progress_data
            progress.save(update_fields=['overall_progress_data'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_alter_lesson_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RunPython(clean_student_progress_data),
    ]